WIP: add SDK compatibility table update action and workflow
paketo-buildpacks/dotnet-core-sdk pull request #256
Opened 2021-09-08 13:54 UTC by sophiewigmore

## Summary

Work in progress to port over the [SDK to runtime compatibility automation task](https://github.com/cloudfoundry/buildpacks-ci/tree/master/tasks/cnb/update-dotnet-sdks-and-compat-table) from concourse to a GHA.

To do: 
- fix tests
- finish workflow itself

## Use Cases

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [ ] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2021-09-21 14:34 UTC, ForestEckhardt requested changes
You'll need to add these files to a .syncignore so they aren't obliterated when updating the workflows

2021-09-22 14:08 UTC, fg-j commented
@sophiewigmore do you have a fork repo or something where you tested these workflows running? Would love to see this flow end to end before merge.

2021-09-22 15:59 UTC, sophiewigmore commented
@fg-j yes, Ihave observed this end to end. 

1. I created a fork and made a fake pull request: https://github.com/sophiewigmore/dotnet-core-sdk/pull/8 with the title `Updates buildpack.toml with new dependency versions: 5.0.401`. 
2. This triggered https://github.com/sophiewigmore/dotnet-core-sdk/runs/3652714901?check_suite_focus=true 
3. That workflow triggered the update workflow to run: https://github.com/sophiewigmore/dotnet-core-sdk/runs/3652717209?check_suite_focus=true, leading to this [update compatibility table commit](https://github.com/sophiewigmore/dotnet-core-sdk/pull/8/commits/30506fd792355a80abc4e3cb3a02c8352b8c9fbc)

2021-09-22 19:40 UTC, ForestEckhardt approved these changes

2021-09-22 19:40 UTC, merged